// Precompiled headers

#if defined __cplusplus
#include <QAbstractItemDelegate>
#include <QAbstractListModel>
#include <QApplication>
#include <QBoxLayout>
#include <QBuffer>
#include <QByteArray>
#include <QCalendarWidget>
#include <QColor>
#include <QCommandLineParser>
#include <QCoreApplication>
#include <QDate>
#include <QDateTime>
#include <QDebug>
#include <QDialog>
#include <QGraphicsSvgItem>
#include <QImage>
#include <QItemSelection>
#include <QItemSelectionModel>
#include <QJsonDocument>
#include <QJsonObject>
#include <QLabel>
#include <QLineEdit>
#include <QList>
#include <QMainWindow>
#include <QMap>
#include <QModelIndex>
#include <QMouseEvent>
#include <QMoveEvent>
#include <QMutex>
#include <QMutexLocker>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QObject>
#include <QPainter>
#include <QPainterPath>
#include <QPixmap>
#include <QPushButton>
#include <QRect>
#include <QRegularExpression>
#include <QRegularExpressionMatch>
#include <QResizeEvent>
#include <QScrollArea>
#include <QSettings>
#include <QSharedPointer>
#include <QSize>
#include <QSizePolicy>
#include <QString>
#include <QStringList>
#include <QStyleOptionViewItem>
#include <QSvgRenderer>
#include <QSystemTrayIcon>
#include <QTime>
#include <QTimer>
#include <QUrl>
#include <QVariant>
#include <QVariantList>
#include <QVariantMap>
#include <QWidget>
#endif
