#ifndef COLORS_H
#define COLORS_H

#include <QColor>

/*
 * Autogenerated color scheme from:
 * https://coolors.co/b7ad99-ff4365-030301-00d9c0-fffff3
 *
 * Icons are Google Material design icons from
 * https://github.com/google/material-design-icons
 *
 */

/**
 * @brief The Colors class Convenience class for retrieving
 *  colors which are part of the Kronos color scheme
 */
class Colors
{
public:
    Colors();
    static QColor khakiWeb();
    static QColor radicalRed();
    static QColor richBlack();
    static QColor turquise();
    static QColor ivory();
};

#endif // COLORS_H
