#ifndef COLORS_H
#define COLORS_H

#include <QColor>

/*
 * Autogenerated color scheme from:
 * https://coolors.co/b7ad99-ff4365-030301-00d9c0-fffff3
 *
 * Icons are Google Material design icons from
 * https://github.com/google/material-design-icons
 *
 */
class Colors
{
public:
    Colors();
    static QColor color1();
    static QColor color2();
    static QColor color3();
    static QColor color4();
    static QColor color5();
};

#endif // COLORS_H
