name: Create a snap from the Kronos binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install qt
      run: sudo apt-get install qt5-default libqt5svg5 libqt5svg5-dev qt5dxcb-plugin
    - name: Install snapcraft
      run: sudo snap install --classic snapcraft
    - name: Install multipass
      run: sudo snap install multipass
    - name: Build kronos and create snap
      working-directory: packages/snap/kronos
      run: sudo snapcraft --destructive-mode
    - name: Save resulting snap as artifact
      uses: actions/upload-artifact@v2
      with:
        name: kronos-snap
        path: packages/snap/kronos/kronos_1.0_amd64.snap

