name: Create a Debian package from the Kronos binary

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: Install qt
      run: sudo apt update
    - run: sudo apt install debhelper devscripts build-essential libgl1-mesa-dev qt6-base-dev libqt6core5compat6-dev libqt6svg6 libqt6svg6-dev libqt6svgwidgets6
    - run: sudo qtchooser -install qt6 $(which qmake6)
    - name: Build kronos and create .deb file
      run: sudo debuild -uc -us && mv ../kronos_1.0_amd64.deb .
    - name: Save resulting package as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: kronos_1.0_amd64.deb
        path: kronos_1.0_amd64.deb

