name: Kronos for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        tools: 'tools_ifw,4.0,qt.tools.ifw.40 tools_qtcreator,4.14.2-0-202103191046,qt.tools.qtcreator'
        arch: win64_mingw81
        version: '5.15.2'
    - name: Build Kronos
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        qmake
        make
    - name: Build unit tests
      shell: cmd
      working-directory: tests
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        qmake kronos-tests.pro
        make
    - name: Copy icon into installer
      shell: cmd
      run: |
        COPY kronos.ico packages\windows-installer\kronos\packages\dk.fork.kronos\data\
    - name: Copy binary into installer
      shell: cmd
      run: |
        COPY release\kronos.exe packages\windows-installer\kronos\packages\dk.fork.kronos\data\
    - name: Copy installer dependencies
      shell: cmd
      working-directory: packages/windows-installer/kronos/packages/dk.fork.kronos/data
      run: |
        windeployqt kronos.exe
    - name: Generate installer
      working-directory: packages/windows-installer/kronos
      shell: cmd
      run: |
        echo %IQTA_TOOLS%
        dir %IQTA_TOOLS%
        dir D:\a\kronos\
        dir D:\a\kronos\Qt\
        dir D:\a\kronos\Qt\Tools\
        dir D:\a\kronos\Qt\Tools\QtInstallerFramework
        D:\a\kronos\Qt\Tools\QtInstallerFramework\4.0\bin\binarycreator.exe -c config\config.xml -p packages ..\..\..\kronos-installer.exe
    - name: Save installer as artifact
      uses: actions/upload-artifact@v2
      with:
        name: kronos-windows-installer
        path: kronos-installer.exe