name: Kronos for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        tools: 'tools_ifw,4.0,qt.tools.ifw.40 tools_qtcreator,4.13.2-0,qt.tools.qtcreator'
        arch: win64_mingw81
        version: '5.15.2'
    - name: Get qmake version
      run: qmake --version
    - name: Get IQTA_TOOLS value
      shell: cmd
      run: echo %IQTA_TOOLS%
    - name: List contents of %IQTA_TOOLS%
      shell: cmd
      run: dir "%IQTA_TOOLS%\QtInstallerFramework\4.0\bin\binarycreator.exe"
    - name: Get binarycreator version
      run: "%IQTA_TOOLS%\QtInstallerFramework\4.0\bin\binarycreator.exe" --version
    - name: Get windeployqt version
      run: windeployqt --version
    - name: Build Kronos
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        qmake
        make
    - name: Build unit tests
      shell: cmd
      working-directory: tests
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        qmake kronos-tests.pro
        make
    - name: Generate installer
      working-directory: packages/windows-installer/kronos
      shell: cmd
      run: |
        "%IQTA_TOOLS%\QtInstallerFramework\4.0\bin\binarycreator.exe" -c config\config.xml -p packages