name: Kronos for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Run qmake for Kronos
      run: qmake
    - name: Build Kronos
      run: make -j8
    - name: Build unit tests
      run: cd tests && qmake kronos-tests.pro && make -j8

